services:
  frontend:
    build:
      context: ./apps/frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
  api:
    build:
      context: ./apps/api
      dockerfile: Dockerfile
    environment:
      - PORT=3001
    ports:
      - "3001:3001"
